[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.26",
    "langchain-openai>=0.3.28",
    "openai>=1.97.1",
    "pandas>=2.3.1",
    "pyodbc>=5.2.0",
    "streamlit>=1.47.0",
]
